image: devfactory/workspace-full:latest
# https://github.com/trilogy-group/workspace-images/blob/main/.gitpod.yml

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      ## Get the data archive
      KEY=2022-07-19_202135
      echo "Downloading from S3"
      aws s3 cp --recursive s3://devgraph-devspaces-demos/dockerdb/edb1/$KEY mysql-data

      docker pull mysql:8.0.29
      docker run -d --name=mysql-server -p 3306:3306 \
                -e MYSQL_ROOT_PASSWORD=mypass       \
                -e MYSQL_DATABASE=testdb            \
                -v /workspace/demoPyMysql/mysql-data:/var/lib/mysql   \
                -v `pwd`/test_db:/test_db           \
                mysql:8.0.29 --max-allowed-packet=67108864 
  

      ## Install Python MySQL Library
      pip3 install mysql-connector-python

    command: docker start mysql-server
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
