image: devfactory/workspace-full:latest
# https://github.com/trilogy-group/workspace-images/blob/main/.gitpod.yml

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |

      docker pull mysql:5.7.38
      docker run -d --name=mysql-server -p 3306:3306 \
                -e MYSQL_ROOT_PASSWORD=mypass       \
                -e MYSQL_DATABASE=testdb            \
                -v mysql-data:/var/lib/mysql        \
                mysql:5.7.38 --max-allowed-packet=67108864 

      ## Download database
      KEY=2022-07-06_231402
      mkdir -p edb1/mysql-data/$KEY
      echo "Downloading from S3"
      #aws s3 cp s3://devgraph-devspaces-demos/dockerdb/edb1/mysql-data/$KEY edb1/mysql-data/
      aws s3 cp --recursive s3://devgraph-devspaces-demos/dockerdb/edb1/mysql-data/$KEY edb1/mysql-data/$KEY/
      find edb1

      ## Install MyDumper, built version
      git clone https://github.com/mydumper/mydumper.git
      git checkout d5346af02868853838b5e1fb0588b647dd751be8
      cd mydumper && cmake . && make && sudo make install && cd ..


      ### Load the database
      mysql -h 127.0.0.1 -u root --password=mypass -e "CREATE DATABASE employees"
      myloader -h 127.0.0.1 -u root  --password=mypass --database=employees --threads=8 --directory edb1/mysql-data/$KEY

      ## Install Python Library
      pip3 install mysql-connector-python



      ## Now, we can stop 
  - command: echo 'start script'
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
